package constants

const (
	QueryLedgerInfoModel          = "model.QueryLedgerInfoByAddress"
	QueryActivityInfoModel        = "model.QueryActivityByUserId"
	SessionBegin                  = "session.Begin"
	SessionCommit                 = "session.Commit"
	InsertFileInfoModel           = "model.InsertFileInfo"
	InsertOrderInfoModel          = "model.InsertOrderInfo"
	UpdateUserBalanceModel        = "model.UpdateUserBalance"
	QueryOrderInfoModel           = "model.QueryOrderInfoById"
	QueryOrderInfo1Model          = "model.QueryOrderInfoByRequestId"
	QueryFileByUkModel            = "model.QueryFileByUk"
	UpdateFileExpireTimeModel     = "model.UpdateFileExpireTime"
	UpdateOrderFileIdModel        = "model.UpdateOrderFileIdById"
	DeleteFileModel               = "model.DeleteFile"
	UpdateFileHashModel           = "model.UpdateFileHash"
	UpdateLedgerInfoModel         = "model.UpdateLedgerInfo"
	UpdateOrderStatusModel        = "model.UpdateOrderStatus"
	QueryMaxExpireModel           = "model.QueryMaxExpireByHash"
	QueryBtfsFileByHashModel      = "model.QueryBtfsFileByHash"
	InsertBtfsFileInfoModel       = "model.InsertBtfsFileInfo"
	UpdateOrderSessionByIdModel   = "model.UpdateOrderSessionById"
	UpdateBtfsFileIdModel         = "model.UpdateBtfsFileId"
	ReopenFileModel               = "model.ReopenFile"
	UpdateBtfsFileExpireTimeModel = "model.UpdateBtfsFileExpireTime"
)
