database:
  connectionUriMaster: "root:123456@tcp(localhost)/soter_test?multiStatements=false"
  connectionUriSlave: "root:123456@tcp(localhost)/soter_test?multiStatements=false"
  maxIdleConn: 50
  maxOpenConn: 100
  maxLifetime: 60

server:
  host: localhost
  port: 6661

env: "DEV"

logger:
  level: 0
  output: ./order.log

slack:
  slackNotificationTimeout: 30
  slackWebhookUrl: https://hooks.slack.com/services/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
  slackPriorityThreshold: 5

kafka:
  topic: ["order"]
  zookeeper: ["localhost:9092"]
  groupId: "order-0"

prometheus:
  port: 2112