database:
  connectionUriMaster: "root:123456@tcp(localhost)/soter_test?multiStatements=false"
  connectionUriSlave: "root:123456@tcp(localhost)/soter_test?multiStatements=false"
  maxIdleConn: 50
  maxOpenConn: 100
  maxLifetime: 60

server:
  host: localhost
  port: 6661

scriptId: 1

defaultTime: 90

logger:
  level: 0
  output: ./order.log