database:
  connectionUriMaster: "root:123456@tcp(localhost)/soter_test?multiStatements=false"
  connectionUriSlave: "root:123456@tcp(localhost)/soter_test?multiStatements=false"
  maxIdleConn: 50
  maxOpenConn: 100
  maxLifetime: 60

server:
  host: "localhost"
  registerHost: "localhost"
  port: 6661
  name: "order-service"
  version: "v1.0"

zookeeper:
  servers: ["localhost:2181"]

env: "DEV"

logger:
  level: 0
  output: ./order.log

slack:
  slackNotificationTimeout: 30
  slackWebhookUrl: https://hooks.slack.com/services/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
  slackPriorityThreshold: 5

kafka:
  topic: ["order"]
  servers: ["localhost:9092"]
  groupId: "order-0"

prometheus:
  port: 2112